@baseUrl = http://localhost:5000/api/v1/employees
# @import ./variables.http

@newEmployeeID = a3eeb793-e05b-4d08-a8ce-ed9408c22a9d
@adminRoleId = 53729686-a368-4eeb-8bfa-cc69b6050d02

### CreateEmployeeAsync - создание сотрудника
POST {{baseUrl}}
Accept: application/json
Content-Type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "email": "string",
  "roles": [
    {
      "id": {{adminRoleId}},
      "name": "string",
      "description": "string"
    }
  ],
  "appliedPromocodesCount": 0
}
### GetEmployeesAsync - получение всех сотрудников
GET {{baseUrl}}

### GetEmployeeByIdAsync - получение сотрудника
GET {{baseUrl}}/{{newEmployeeID}}
Accept: application/json
