@baseUrl = http://localhost:5000/api/v1/employees
# @import ./variables.http

@employeeToDeleteId = "423876d5-5ae7-4a83-9c7b-eb9a54e14f2f"
@adminROleId = "00000000-0000-0000-0000-000000000000"

################################################## DELETE AN EMPLOYEE ##################################################

################################################## Создание сотрудника ##################################################
### CreateEmployeeAsync
POST {{baseUrl}}
Accept: application/json
Content-Type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "email": "string",
  "roles": [
    {
      "id": {{adminROleId}},
      "name": "string",
      "description": "string"
    }
  ],
  "appliedPromocodesCount": 0
}

################################################## Удаление сотрудника ##################################################
### DeleteEmployeeByIdAsync
DELETE {{baseUrl}}/{{employeeToDeleteId}}
Accept: application/json

################################################## Получение сотрудника ##################################################
### GetEmployeeByIdAsync
GET {{baseUrl}}/{{employeeToDeleteId}}
Accept: application/json
