@baseUrl = http://localhost:5000/api/v1/employees
# @import ./variables.http

################################################## Обзор начального состояния ##################################################
### GetEmployeesAsync
GET {{baseUrl}}

### GetEmployeeByIdAsync
GET {{baseUrl}}/{{user01Id}}

################################################## Удаление сотрудника ##################################################
###

###
