@baseUrl = http://localhost:5000/api/v1/employees
# @import ./variables.http

@employeeToDeleteId = 1282ba61-6bdd-462d-9229-894e3e175e86
@adminRoleId = 53729686-a368-4eeb-8bfa-cc69b6050d02

### CreateEmployeeAsync - создание сотрудника
POST {{baseUrl}}
Accept: application/json
Content-Type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "email": "string",
  "roles": [
    {
      "id": {{adminRoleId}},
      "name": "string",
      "description": "string"
    }
  ],
  "appliedPromocodesCount": 0
}

### DeleteEmployeeByIdAsync - удаление сотрудника
DELETE {{baseUrl}}/{{employeeToDeleteId}}
Accept: application/json

### GetEmployeeByIdAsync - получение сотрудника
GET {{baseUrl}}/{{employeeToDeleteId}}
Accept: application/json
