@baseUrl = http://localhost:5000/api/v1/employees
# @import ./variables.http

@employeeToUpdateId = "991876d5-c8e7-4a11-9c7b-cd9a54e4c32f"
@partnerManagerRoleId = "00000000-0000-0000-0000-000000000000"

################################################## UPDATE AN EMPLOYEE ##################################################

################################################## Создание сотрудника ##################################################
### GetEmployeesAsync
POST {{baseUrl}}
Accept: application/json
Content-Type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "email": "string",
  "roles": [
    {
      "id": {{partnerManagerRoleId}},
      "name": "string",
      "description": "string"
    }
  ],
  "appliedPromocodesCount": 0
}

################################################## Изменение сотрудника ##################################################
###
PUT {{baseUrl}}/{{employeeToUpdateId}}
Accept: application/json
Content-Type: application/json

{
  "id": {{employeeToUpdateId}},
  "firstName": "string",
  "lastName": "string",
  "email": "new email",
  "roles": [
    {
      "id": "string",
      "name": "string",
      "description": "string"
    }
  ],
  "appliedPromocodesCount": 0
}

################################################## Получение сотрудника ##################################################
### GetEmployeeByIdAsync
GET {{baseUrl}}/{{employeeToUpdateId}}
Accept: application/json