@baseUrl = http://localhost:5000/api/v1/employees
# @import ./variables.http

@employeeToUpdateId = 991876d5-c8e7-4a11-9c7b-cd9a54e4c32f
@partnerManagerRoleId = b0ae7aac-5493-45cd-ad16-87426a5e7665

### CreateEmployeeAsync - создание сотрудника
POST {{baseUrl}}
Accept: application/json
Content-Type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "email": "string",
  "roles": [
    {
      "id": {{partnerManagerRoleId}},
      "name": "string",
      "description": "string"
    }
  ],
  "appliedPromocodesCount": 0
}

### TODO: - изменение сотрудника
PUT {{baseUrl}}/{{employeeToUpdateId}}
Accept: application/json
Content-Type: application/json

{
  "id": {{employeeToUpdateId}},
  "firstName": "string",
  "lastName": "string",
  "email": "new email",
  "roles": [
    {
      "id": "string",
      "name": "string",
      "description": "string"
    }
  ],
  "appliedPromocodesCount": 0
}

### GetEmployeeByIdAsync - получение сотрудника
GET {{baseUrl}}/{{employeeToUpdateId}}
Accept: application/json